# Generated by Django 6.0.7 on 2026-08-02 09:14

import after_sales.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0001_after_sales_phase07'),
        ('media_library', '0001_media_library_phase08'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftersalesattachment',
            name='media_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_attachments', to='media_library.mediaasset'),
        ),
        migrations.AlterField(
            model_name='aftersalesattachment',
            name='file',
            field=models.FileField(blank=True, upload_to=after_sales.models.after_sales_attachment_path),
        ),
    ]
