# Generated by Django 6.0.7 on 2026-08-02 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0003_salesscorepolicy_salesscoreevent_salesgoal_and_more'),
        ('customers', '0002_customer_commercial_source_customer_partner_and_more'),
        ('fleet', '0001_initial'),
        ('production', '0001_initial'),
        ('quotes', '0004_quoteacceptance'),
        ('salespeople', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalEventSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'sequência de eventos',
                'verbose_name_plural': 'sequências de eventos',
            },
        ),
        migrations.CreateModel(
            name='OperationalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('commercial_follow_up', 'Follow-up comercial'), ('customer_meeting', 'Reunião com cliente'), ('technical_visit', 'Visita técnica'), ('measurement', 'Medição'), ('quote_presentation', 'Apresentação de orçamento'), ('production_task', 'Tarefa de produção'), ('material_pickup', 'Retirada de material'), ('delivery', 'Entrega'), ('installation', 'Instalação'), ('quality_return', 'Retorno de qualidade'), ('technical_assistance', 'Assistência técnica'), ('rework_visit', 'Visita de retrabalho'), ('internal_meeting', 'Reunião interna'), ('other', 'Outro')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('rescheduled', 'Reagendado'), ('no_show', 'Não comparecimento'), ('blocked', 'Bloqueado')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('external_responsible', models.CharField(blank=True, max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('confirmation_status', models.CharField(choices=[('pending', 'Não confirmado'), ('confirmed', 'Confirmado'), ('attempted', 'Tentativa registrada'), ('declined', 'Recusado')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_channel', models.CharField(blank=True, choices=[('phone', 'Telefone'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('in_person', 'Presencial'), ('other', 'Outro')], max_length=20)),
                ('confirmation_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('block_reason', models.TextField(blank=True)),
                ('conflict_override_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_events', to='salespeople.salesperson')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_events_assigned', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to='customers.customer')),
                ('delivery_schedule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_event', to='production.deliveryschedule')),
                ('installation_schedule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_event', to='production.installationschedule')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to='commercial.lead')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to='production.productionorder')),
                ('production_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to='production.productionpiece')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to='quotes.quote')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to='production.salesorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['start_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement_type', models.CharField(choices=[('initial', 'Inicial'), ('final', 'Final'), ('confirmation', 'Confirmação'), ('rework', 'Retrabalho')], default='initial', max_length=20)),
                ('required_documents', models.TextField(blank=True)),
                ('customer_confirmed', models.BooleanField(default=False)),
                ('measurement_completed', models.BooleanField(default=False)),
                ('measurement_notes', models.TextField(blank=True)),
                ('textual_measurements', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_appointments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='scheduling.operationalevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalEventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Criado'), ('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('started', 'Iniciado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('rescheduled', 'Reagendado'), ('blocked', 'Bloqueado'), ('unblocked', 'Desbloqueado'), ('assignment_changed', 'Responsável alterado'), ('vehicle_changed', 'Veículo alterado'), ('conflict_overridden', 'Conflito sobrescrito'), ('no_show', 'Não comparecimento'), ('confirmation_attempted', 'Tentativa de confirmação')], max_length=40)),
                ('old_start_at', models.DateTimeField(blank=True, null=True)),
                ('old_end_at', models.DateTimeField(blank=True, null=True)),
                ('new_start_at', models.DateTimeField(blank=True, null=True)),
                ('new_end_at', models.DateTimeField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_event_history', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='scheduling.operationalevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='operationalevent',
            index=models.Index(fields=['start_at', 'end_at'], name='scheduling__start_a_ccb0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalevent',
            index=models.Index(fields=['status', 'start_at'], name='scheduling__status_3167ba_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalevent',
            index=models.Index(fields=['event_type', 'start_at'], name='scheduling__event_t_f2baf8_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalevent',
            index=models.Index(fields=['assigned_user', 'start_at'], name='scheduling__assigne_6bba34_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalevent',
            index=models.Index(fields=['assigned_salesperson', 'start_at'], name='scheduling__assigne_6b7162_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalevent',
            index=models.Index(fields=['city', 'start_at'], name='scheduling__city_6f9491_idx'),
        ),
    ]
