# Generated by Django 6.0.7 on 2026-08-02 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0001_after_sales_phase07'),
        ('scheduling', '0001_operational_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalevent',
            name='after_sales_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to='after_sales.aftersalescase'),
        ),
    ]
