# Generated by Django 5.0.11 on 2026-07-25 01:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('asset_code', models.CharField(max_length=60, unique=True)),
                ('plate', models.CharField(max_length=10, unique=True)),
                ('renavam', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('chassis', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=100)),
                ('manufacture_year', models.PositiveIntegerField(blank=True, null=True)),
                ('model_year', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasolina'), ('ethanol', 'Etanol'), ('flex', 'Flex'), ('diesel', 'Diesel'), ('electric', 'Elétrico'), ('hybrid', 'Híbrido'), ('other', 'Outro')], default='flex', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('odometer', models.PositiveIntegerField(default=0)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('maintenance', 'Em manutenção'), ('inactive', 'Inativo'), ('sold', 'Vendido'), ('accident', 'Sinistro')], default='active', max_length=20)),
                ('licensing_expiration', models.DateField(blank=True, null=True)),
                ('insurance_expiration', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_vehicles', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'veículo',
                'verbose_name_plural': 'veículos',
                'ordering': ['plate'],
            },
        ),
    ]
