# Generated by Django 5.0.11 on 2026-07-25 01:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventiva'), ('predictive', 'Preditiva'), ('inspection', 'Inspeção'), ('legal', 'Legal'), ('calibration', 'Calibração'), ('cleaning', 'Limpeza'), ('lubrication', 'Lubrificação')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('critical', 'Crítica')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('scheduled', 'Agendada'), ('in_progress', 'Em andamento'), ('waiting_parts', 'Aguardando peças'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('reported_problem', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('service_performed', models.TextField(blank=True)),
                ('supplier', models.CharField(blank=True, max_length=160)),
                ('usage_at_service', models.PositiveIntegerField(blank=True, null=True)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_orders', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'ordem de manutenção',
                'verbose_name_plural': 'ordens de manutenção',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='maintenance-attachments/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('maintenance_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.maintenanceorder')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=180)),
                ('part_number', models.CharField(blank=True, max_length=80)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('maintenance_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='maintenance.maintenanceorder')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventiva'), ('predictive', 'Preditiva'), ('inspection', 'Inspeção'), ('legal', 'Legal'), ('calibration', 'Calibração'), ('cleaning', 'Limpeza'), ('lubrication', 'Lubrificação')], max_length=20)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_usage', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_unit', models.CharField(blank=True, choices=[('km', 'Km'), ('hours', 'Horas'), ('cycles', 'Ciclos'), ('days', 'Dias'), ('months', 'Meses')], max_length=20)),
                ('last_performed_date', models.DateField(blank=True, null=True)),
                ('last_performed_usage', models.PositiveIntegerField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('next_due_usage', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'plano de manutenção',
                'verbose_name_plural': 'planos de manutenção',
                'ordering': ['next_due_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='maintenance.maintenanceplan'),
        ),
    ]
