# Generated by Django 6.0.7 on 2026-08-02 09:14

import django.db.models.deletion
import django.utils.timezone
import media_library.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('after_sales', '0001_after_sales_phase07'),
        ('commercial', '0003_salesscorepolicy_salesscoreevent_salesgoal_and_more'),
        ('customers', '0002_customer_commercial_source_customer_partner_and_more'),
        ('materials', '0003_rename_materials_s_referen_6a0fbd_idx_materials_s_referen_a766f2_idx_and_more'),
        ('production', '0001_initial'),
        ('quotes', '0004_quoteacceptance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAssetSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MediaCollectionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=30, unique=True)),
                ('file', models.FileField(upload_to=media_library.models.media_asset_upload_to)),
                ('thumbnail', models.ImageField(blank=True, upload_to=media_library.models.media_thumbnail_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('stored_filename', models.CharField(blank=True, max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('document', 'Documento'), ('technical_drawing', 'Desenho técnico'), ('measurement_file', 'Arquivo de medição'), ('quality_report', 'Relatório de qualidade'), ('customer_message', 'Mensagem do cliente'), ('invoice_reference', 'Referência de fatura'), ('other', 'Outro')], default='image', max_length=40)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Enviado'), ('classified', 'Classificado'), ('under_review', 'Em revisão'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('archived', 'Arquivado'), ('deleted', 'Excluído')], default='uploaded', max_length=30)),
                ('visibility', models.CharField(choices=[('private', 'Privado'), ('internal', 'Interno'), ('customer_related', 'Relacionado ao cliente'), ('portfolio_candidate', 'Candidato a portfólio'), ('public_approved', 'Aprovado para uso público')], default='private', max_length=30)),
                ('technical_review_status', models.CharField(choices=[('technical_pending', 'Pendente'), ('technical_approved', 'Aprovado'), ('technical_rejected', 'Rejeitado')], default='technical_pending', max_length=30)),
                ('capture_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_portfolio_approved', models.BooleanField(default=False)),
                ('portfolio_approved_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('deletion_requested', models.BooleanField(default=False)),
                ('deletion_reason', models.TextField(blank=True)),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('after_sales_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='after_sales.aftersalescase')),
                ('consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='after_sales.mediausageconsent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='customers.customer')),
                ('deletion_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('delivery_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='production.deliveryschedule')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='media_library.mediaasset')),
                ('installation_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='production.installationschedule')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='commercial.lead')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='materials.material')),
                ('portfolio_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_approved_media', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='production.productionorder')),
                ('production_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='production.productionpiece')),
                ('production_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='production.productionstage')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='quotes.quote')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='production.salesorder')),
                ('slab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='materials.materialslab')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_media_assets', to=settings.AUTH_USER_MODEL)),
                ('warranty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='after_sales.warrantyrecord')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('uploaded', 'Upload'), ('duplicate_detected', 'Duplicidade detectada'), ('classified', 'Classificado'), ('updated', 'Atualizado'), ('linked', 'Vinculado'), ('unlinked', 'Desvinculado'), ('reviewed', 'Revisado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('portfolio_approved', 'Aprovado para portfólio'), ('portfolio_removed', 'Removido do portfólio'), ('archived', 'Arquivado'), ('deletion_requested', 'Exclusão solicitada'), ('thumbnail_generated', 'Miniatura gerada')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='media_library.mediaasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('requires_consent', models.BooleanField(default=False)),
                ('is_portfolio_eligible', models.BooleanField(default=False)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='media_library.mediacategory'),
        ),
        migrations.CreateModel(
            name='MediaCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('collection_type', models.CharField(choices=[('customer_project', 'Projeto do cliente'), ('production', 'Produção'), ('installation', 'Instalação'), ('before_after', 'Antes e depois'), ('portfolio', 'Portfólio'), ('after_sales', 'Pós-venda'), ('material_catalog', 'Catálogo de materiais'), ('custom', 'Personalizado')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('under_review', 'Em revisão'), ('approved', 'Aprovado'), ('archived', 'Arquivado')], default='draft', max_length=30)),
                ('after_sales_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_collections', to='after_sales.aftersalescase')),
                ('cover_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_collections', to='media_library.mediaasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_collections', to='customers.customer')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_collections', to='production.productionorder')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_collections', to='production.salesorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BeforeAfterPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('approved_for_portfolio', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='before_after_pairs', to='customers.customer')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='before_after_pairs', to='production.salesorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('after_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='after_pairs', to='media_library.mediaasset')),
                ('before_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='before_pairs', to='media_library.mediaasset')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='before_after_pairs', to='media_library.mediacollection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('technical_pending', 'Pendente'), ('technical_approved', 'Aprovado'), ('technical_rejected', 'Rejeitado')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='media_library.mediaasset')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', to='media_library.mediatag'),
        ),
        migrations.CreateModel(
            name='PublicationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('website', 'Site'), ('blog', 'Blog'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('portfolio', 'Portfólio'), ('google_business_profile', 'Google Meu Negócio (planejamento)'), ('other', 'Outro')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('candidate', 'Candidato'), ('scheduled', 'Planejado'), ('cancelled', 'Cancelado'), ('completed_manual', 'Concluído manualmente')], default='candidate', max_length=30)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('caption', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_publication_candidates', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_candidates', to='media_library.mediaasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAssetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('customer', 'Cliente'), ('lead', 'Lead'), ('quote', 'Orçamento'), ('sales_order', 'Pedido'), ('production_order', 'Ordem de produção'), ('production_piece', 'Peça'), ('production_stage', 'Etapa'), ('material', 'Material'), ('slab', 'Chapa'), ('delivery_schedule', 'Entrega'), ('installation_schedule', 'Instalação'), ('after_sales_case', 'Pós-venda'), ('warranty', 'Garantia')], max_length=40)),
                ('target_id', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='media_library.mediaasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='media_libra_target__dbc996_idx')],
                'unique_together': {('asset', 'target_type', 'target_id')},
            },
        ),
        migrations.CreateModel(
            name='MediaCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_cover', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='media_library.mediaasset')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='media_library.mediacollection')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('collection', 'asset')},
            },
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['status', 'uploaded_at'], name='media_libra_status_211d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['visibility', 'status'], name='media_libra_visibil_6e124c_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['media_type', 'status'], name='media_libra_media_t_836562_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['is_portfolio_approved', 'status'], name='media_libra_is_port_daf333_idx'),
        ),
    ]
