# Generated by Django 5.0.11 on 2026-07-25 01:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('event_type', models.CharField(choices=[('authentication', 'Autenticação'), ('authorization', 'Autorização'), ('create', 'Criação'), ('update', 'Alteração'), ('deactivate', 'Desativação'), ('reactivate', 'Reativação'), ('delete', 'Exclusão'), ('view', 'Visualização'), ('export', 'Exportação'), ('print', 'Impressão'), ('approve', 'Aprovação'), ('send', 'Envio'), ('cancel', 'Cancelamento'), ('maintenance', 'Manutenção'), ('configuration', 'Configuração')], max_length=30)),
                ('module', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=12)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('denied', 'Negado'), ('failed', 'Falhou')], default='success', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de auditoria',
                'verbose_name_plural': 'eventos de auditoria',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=80)),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('logout_reason', models.CharField(blank=True, choices=[('manual', 'Manual'), ('expired', 'Expirada'), ('revoked', 'Revogada'), ('password_changed', 'Senha alterada'), ('user_deactivated', 'Usuário desativado'), ('unknown', 'Desconhecida')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sessão de usuário',
                'verbose_name_plural': 'sessões de usuários',
                'ordering': ['-login_at'],
                'indexes': [models.Index(fields=['session_key', 'is_active'], name='audit_users_session_a8f5d8_idx')],
            },
        ),
    ]
