# Generated by Django 5.0.11 on 2026-07-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(max_length=40, verbose_name='telefone')),
                ('cidade', models.CharField(max_length=120, verbose_name='cidade')),
                ('ambiente', models.CharField(max_length=80, verbose_name='ambiente/projeto')),
                ('medidas', models.TextField(blank=True, verbose_name='medidas/informações técnicas')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contatado'), ('qualified', 'Qualificado'), ('closed', 'Fechado'), ('discarded', 'Descartado')], default='new', max_length=20, verbose_name='status')),
                ('source_path', models.CharField(blank=True, max_length=255, verbose_name='origem')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user-agent')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='notificação enviada em')),
                ('notification_error', models.TextField(blank=True, verbose_name='erro de notificação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'solicitação de contato',
                'verbose_name_plural': 'solicitações de contato',
                'ordering': ['-created_at'],
            },
        ),
    ]
