# Generated by Django 5.0.11 on 2026-07-25 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at'], 'permissions': [('assign_contactrequest', 'Pode atribuir solicitações de contato')], 'verbose_name': 'solicitação de contato', 'verbose_name_plural': 'solicitações de contato'},
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contact_requests', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.CreateModel(
            name='ContactRequestAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('lead_created', 'Lead criado'), ('status_changed', 'Status alterado'), ('assigned', 'Responsável atribuído'), ('note_added', 'Observação adicionada')], max_length=40, verbose_name='ação')),
                ('previous_value', models.TextField(blank=True, verbose_name='valor anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='valor novo')),
                ('source', models.CharField(blank=True, max_length=80, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_request_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('contact_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='institutional.contactrequest', verbose_name='solicitação')),
            ],
            options={
                'verbose_name': 'histórico da solicitação',
                'verbose_name_plural': 'históricos das solicitações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_request_notes', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('contact_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='institutional.contactrequest', verbose_name='solicitação')),
            ],
            options={
                'verbose_name': 'observação interna',
                'verbose_name_plural': 'observações internas',
                'ordering': ['-created_at'],
            },
        ),
    ]
