# Generated by Django 5.0.11 on 2026-07-26 14:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0002_alter_contactrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='ano')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='próximo número')),
            ],
            options={
                'verbose_name': 'sequência de orçamento',
                'verbose_name_plural': 'sequências de orçamento',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='título/projeto')),
                ('customer_name', models.CharField(max_length=160, verbose_name='cliente')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('customer_phone', models.CharField(max_length=40, verbose_name='telefone')),
                ('city', models.CharField(max_length=120, verbose_name='cidade')),
                ('stage', models.CharField(choices=[('qualification', 'Qualificação'), ('quotation', 'Orçamento'), ('quotation_sent', 'Orçamento enviado'), ('negotiation', 'Negociação'), ('won', 'Ganho'), ('lost', 'Perdido')], default='qualification', max_length=30, verbose_name='etapa')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor estimado')),
                ('probability', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='probabilidade')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='previsão de fechamento')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('lost_reason', models.CharField(blank=True, choices=[('price', 'Preço'), ('deadline', 'Prazo'), ('competition', 'Concorrência'), ('customer_gave_up', 'Cliente desistiu'), ('no_response', 'Sem retorno'), ('technically_unfeasible', 'Inviável tecnicamente'), ('other', 'Outro')], max_length=40, verbose_name='motivo da perda')),
                ('lost_notes', models.TextField(blank=True, verbose_name='observações da perda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('contact_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity', to='institutional.contactrequest', verbose_name='lead de origem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'oportunidade comercial',
                'verbose_name_plural': 'oportunidades comerciais',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('opportunity_created', 'Oportunidade criada'), ('stage_changed', 'Etapa alterada'), ('responsible_changed', 'Responsável alterado'), ('estimated_value_changed', 'Valor estimado alterado'), ('quote_created', 'Orçamento criado'), ('quote_sent', 'Orçamento enviado'), ('quote_accepted', 'Orçamento aceito'), ('quote_rejected', 'Orçamento rejeitado')], max_length=50, verbose_name='ação')),
                ('previous_value', models.TextField(blank=True, verbose_name='valor anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='valor novo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='institutional.opportunity', verbose_name='oportunidade')),
            ],
            options={
                'verbose_name': 'histórico da oportunidade',
                'verbose_name_plural': 'históricos das oportunidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='número')),
                ('revision', models.PositiveIntegerField(default=0, verbose_name='revisão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronto'), ('sent', 'Enviado'), ('accepted', 'Aceito'), ('rejected', 'Rejeitado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='desconto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='institutional.opportunity', verbose_name='oportunidade')),
            ],
            options={
                'verbose_name': 'orçamento',
                'verbose_name_plural': 'orçamentos',
                'ordering': ['-created_at', '-revision'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='quantidade')),
                ('unit', models.CharField(choices=[('un', 'un'), ('m', 'm'), ('m2', 'm²'), ('m3', 'm³'), ('service', 'serviço')], default='un', max_length=20, verbose_name='unidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço unitário')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='institutional.quote', verbose_name='orçamento')),
            ],
            options={
                'verbose_name': 'item de orçamento',
                'verbose_name_plural': 'itens de orçamento',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('number', 'revision'), name='unique_quote_number_revision'),
        ),
    ]
