# Generated by Django 5.0.11 on 2026-07-26 14:29

import django.db.models.deletion
import src.institutional.infrastructure.django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0003_quotesequence_opportunity_opportunityauditlog_quote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunityauditlog',
            name='action',
            field=models.CharField(choices=[('opportunity_created', 'Oportunidade criada'), ('stage_changed', 'Etapa alterada'), ('responsible_changed', 'Responsável alterado'), ('estimated_value_changed', 'Valor estimado alterado'), ('quote_created', 'Orçamento criado'), ('quote_sent', 'Orçamento enviado'), ('quote_accepted', 'Orçamento aceito'), ('quote_rejected', 'Orçamento rejeitado'), ('quote_document_generated', 'Documento de orçamento gerado'), ('quote_document_voided', 'Documento de orçamento anulado'), ('quote_delivery_requested', 'Envio de orçamento solicitado'), ('quote_send_failed', 'Envio de orçamento falhou'), ('quote_resent', 'Orçamento reenviado'), ('quote_revision_created', 'Revisão de orçamento criada')], max_length=50, verbose_name='ação'),
        ),
        migrations.CreateModel(
            name='QuoteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(verbose_name='revisão')),
                ('document_number', models.CharField(max_length=40, verbose_name='documento')),
                ('status', models.CharField(choices=[('generated', 'Gerado'), ('sent', 'Enviado'), ('void', 'Anulado')], default='generated', max_length=20, verbose_name='status')),
                ('snapshot_data', models.JSONField(verbose_name='snapshot')),
                ('snapshot_fingerprint', models.CharField(max_length=64, verbose_name='fingerprint')),
                ('file', models.FileField(blank=True, upload_to=src.institutional.infrastructure.django.models.quote_document_upload_to, verbose_name='arquivo')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='checksum SHA-256')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='gerado em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_quote_documents', to=settings.AUTH_USER_MODEL, verbose_name='gerado por')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='institutional.quote', verbose_name='orçamento')),
            ],
            options={
                'verbose_name': 'documento de orçamento',
                'verbose_name_plural': 'documentos de orçamento',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], default='email', max_length=20, verbose_name='canal')),
                ('recipient', models.EmailField(max_length=254, verbose_name='destinatário')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='solicitado em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='institutional.quote', verbose_name='orçamento')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_quote_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='institutional.quotedocument', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'entrega de orçamento',
                'verbose_name_plural': 'entregas de orçamento',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='quotedocument',
            constraint=models.UniqueConstraint(fields=('quote', 'revision', 'snapshot_fingerprint'), name='unique_quote_document_snapshot'),
        ),
    ]
