# Generated by Django 6.0.7 on 2026-08-02 04:41

import django.db.models.deletion
import materials.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
        ('customers', '0002_customer_commercial_source_customer_partner_and_more'),
        ('salespeople', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('current', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('project_description', models.TextField(blank=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[materials.models.validate_non_negative])),
                ('status', models.CharField(choices=[('new', 'Novo'), ('triage', 'Triagem'), ('assigned', 'Atribuído'), ('contacted', 'Contato realizado'), ('qualified', 'Qualificado'), ('measurement_scheduled', 'Medição agendada'), ('measurement_completed', 'Medição concluída'), ('quote_preparation', 'Preparação de orçamento'), ('quote_sent', 'Orçamento enviado'), ('negotiation', 'Negociação'), ('won', 'Ganho'), ('lost', 'Perdido'), ('disqualified', 'Desqualificado')], default='new', max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20)),
                ('probability', models.PositiveSmallIntegerField(default=10)),
                ('first_contact_at', models.DateTimeField(blank=True, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('loss_notes', models.TextField(blank=True)),
                ('external_source', models.CharField(blank=True, max_length=80)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('assigned_salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='salespeople.salesperson')),
                ('commercial_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='commercial.commercialsource')),
                ('contact_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='commercial.contactchannel')),
                ('converted_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='customers.customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('loss_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='commercial.lossreason')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='commercial.commercialpartner')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='commercial.projecttype')),
                ('service_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='commercial.serviceregion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('note', 'Observação'), ('call', 'Ligação'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('meeting', 'Reunião'), ('site_visit', 'Visita'), ('measurement', 'Medição'), ('proposal', 'Proposta'), ('follow_up', 'Follow-up'), ('status_change', 'Mudança de status'), ('assignment', 'Atribuição'), ('conversion', 'Conversão'), ('loss', 'Perda'), ('reopening', 'Reabertura'), ('other', 'Outro')], max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to='commercial.contactchannel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_activities_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='commercial.lead')),
            ],
            options={
                'verbose_name': 'atividade do lead',
                'verbose_name_plural': 'atividades do lead',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks_cancelled', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='commercial.lead')),
            ],
            options={
                'verbose_name': 'tarefa do lead',
                'verbose_name_plural': 'tarefas do lead',
                'ordering': ['due_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='commercial_lead_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_salesperson'], name='commercial_lead_sales_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['commercial_source'], name='commercial_lead_source_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority'], name='commercial_lead_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_follow_up_at'], name='commercial_lead_follow_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='commercial_lead_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('probability__gte', 0), ('probability__lte', 100)), name='commercial_lead_probability_range'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', ''), ('external_source__gt', '')), fields=('external_source', 'external_id'), name='commercial_lead_external_unique'),
        ),
        migrations.AddIndex(
            model_name='leadtask',
            index=models.Index(fields=['status', 'due_at'], name='commercial_leadtask_due_idx'),
        ),
    ]
