# Generated by Django 6.0.7 on 2026-08-02 04:51

import django.db.models.deletion
import django.utils.timezone
import materials.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_leadsequence_lead_leadactivity_leadtask_and_more'),
        ('salespeople', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesScorePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('points_lead_created', models.IntegerField(default=0)),
                ('points_first_contact', models.IntegerField(default=10)),
                ('points_lead_qualified', models.IntegerField(default=5)),
                ('points_measurement_completed', models.IntegerField(default=5)),
                ('points_quote_created', models.IntegerField(default=0)),
                ('points_quote_sent', models.IntegerField(default=20)),
                ('points_follow_up_completed', models.IntegerField(default=10)),
                ('points_lead_won', models.IntegerField(default=50)),
                ('points_sales_value_factor', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('penalty_overdue_follow_up', models.PositiveIntegerField(default=5)),
                ('penalty_unattended_lead', models.PositiveIntegerField(default=10)),
                ('penalty_lost_without_reason', models.PositiveIntegerField(default=10)),
                ('maximum_daily_score', models.PositiveIntegerField(default=0, help_text='0 = sem limite diário')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Políticas de score comercial',
                'ordering': ['-valid_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SalesScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('lead_created', 'Lead criado'), ('first_contact', 'Primeiro contato'), ('lead_qualified', 'Lead qualificado'), ('measurement_completed', 'Medição concluída'), ('quote_created', 'Orçamento criado'), ('quote_sent', 'Orçamento enviado'), ('follow_up_completed', 'Follow-up concluído'), ('lead_won', 'Lead ganho'), ('sales_value_bonus', 'Bônus por valor vendido'), ('overdue_follow_up_penalty', 'Follow-up vencido'), ('unattended_lead_penalty', 'Lead sem resposta'), ('lost_without_reason_penalty', 'Perda sem motivo'), ('manual_adjustment', 'Ajuste manual')], max_length=40)),
                ('points', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reference_label', models.CharField(blank=True, max_length=200)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_score_events', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_events', to='salespeople.salesperson')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='commercial.salesscorepolicy')),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SalesGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual'), ('custom', 'Personalizado')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('lead_goal', models.PositiveIntegerField(default=0)),
                ('contact_goal', models.PositiveIntegerField(default=0)),
                ('quote_goal', models.PositiveIntegerField(default=0)),
                ('won_lead_goal', models.PositiveIntegerField(default=0)),
                ('sales_value_goal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[materials.models.validate_non_negative])),
                ('conversion_goal', models.PositiveSmallIntegerField(default=0, validators=[materials.models.validate_percentage])),
                ('response_time_goal_minutes', models.PositiveIntegerField(default=0)),
                ('follow_up_compliance_goal', models.PositiveSmallIntegerField(default=0, validators=[materials.models.validate_percentage])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_goals', to='salespeople.salesperson')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'salesperson__display_name'],
                'indexes': [models.Index(fields=['salesperson', 'is_active'], name='commercial__salespe_33c68a_idx'), models.Index(fields=['start_date', 'end_date'], name='commercial__start_d_97eacc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='sales_goal_valid_date_range'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('salesperson', 'period_type', 'start_date', 'end_date'), name='unique_active_sales_goal_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='salesscorepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='score_policy_valid_date_range'),
        ),
        migrations.AddIndex(
            model_name='salesscoreevent',
            index=models.Index(fields=['salesperson', 'period_date'], name='commercial__salespe_0d3695_idx'),
        ),
        migrations.AddIndex(
            model_name='salesscoreevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='commercial__event_t_3aaae7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesscoreevent',
            index=models.Index(fields=['reference_type', 'reference_id'], name='commercial__referen_939bc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesscoreevent',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_id__isnull', False)), fields=('salesperson', 'event_type', 'reference_type', 'reference_id'), name='unique_score_event_reference'),
        ),
    ]
