PERMISSIONS = [
    ("dashboard.view", "Visualizar dashboard", "dashboard", "view"),
    ("users.view", "Visualizar usuários", "users", "view"),
    ("users.create", "Criar usuários", "users", "create"),
    ("users.update", "Alterar usuários", "users", "update"),
    ("users.deactivate", "Desativar usuários", "users", "deactivate"),
    ("users.manage_roles", "Gerenciar cargos de usuários", "users", "manage_roles"),
    ("roles.view", "Visualizar cargos", "roles", "view"),
    ("roles.create", "Criar cargos", "roles", "create"),
    ("roles.update", "Alterar cargos", "roles", "update"),
    ("roles.delete", "Excluir cargos", "roles", "delete"),
    (
        "roles.manage_permissions",
        "Gerenciar permissões de cargos",
        "roles",
        "manage_permissions",
    ),
    ("customers.view", "Visualizar clientes", "customers", "view"),
    ("customers.create", "Criar clientes", "customers", "create"),
    ("customers.update", "Alterar clientes", "customers", "update"),
    ("customers.deactivate", "Desativar clientes", "customers", "deactivate"),
    ("customers.export", "Exportar clientes", "customers", "export"),
    ("salespeople.view", "Visualizar vendedores", "salespeople", "view"),
    ("salespeople.create", "Criar vendedores", "salespeople", "create"),
    ("salespeople.update", "Alterar vendedores", "salespeople", "update"),
    ("salespeople.deactivate", "Desativar vendedores", "salespeople", "deactivate"),
    (
        "salespeople.view_team",
        "Visualizar equipe comercial",
        "salespeople",
        "view_team",
    ),
    ("quotes.view", "Visualizar orçamentos", "quotes", "view"),
    ("quotes.view_own", "Visualizar próprios orçamentos", "quotes", "view_own"),
    ("quotes.view_team", "Visualizar orçamentos da equipe", "quotes", "view_team"),
    ("quotes.create", "Criar orçamentos", "quotes", "create"),
    ("quotes.update", "Alterar orçamentos", "quotes", "update"),
    ("quotes.approve", "Aprovar orçamentos", "quotes", "approve"),
    ("quotes.send", "Enviar orçamentos", "quotes", "send"),
    ("quotes.cancel", "Cancelar orçamentos", "quotes", "cancel"),
    ("quotes.accept", "Aceitar orçamentos", "quotes", "accept"),
    ("quotes.refuse", "Recusar orçamentos", "quotes", "refuse"),
    ("quotes.accept_expired", "Aceitar orçamento expirado", "quotes", "accept_expired"),
    ("quotes.view_cost", "Visualizar custos de orçamentos", "quotes", "view_cost"),
    ("quotes.view_margin", "Visualizar margem de orçamentos", "quotes", "view_margin"),
    (
        "quotes.override_minimum_price",
        "Liberar preço abaixo do mínimo",
        "quotes",
        "override_minimum_price",
    ),
    (
        "quotes.manage_policy",
        "Gerenciar política comercial",
        "quotes",
        "manage_policy",
    ),
    ("materials.view", "Visualizar materiais", "materials", "view"),
    ("materials.create", "Criar materiais", "materials", "create"),
    ("materials.update", "Alterar materiais", "materials", "update"),
    ("materials.deactivate", "Desativar materiais", "materials", "deactivate"),
    (
        "materials.change_price",
        "Alterar preços de materiais",
        "materials",
        "change_price",
    ),
    ("assets.view", "Visualizar ativos", "assets", "view"),
    ("assets.create", "Criar ativos", "assets", "create"),
    ("assets.update", "Alterar ativos", "assets", "update"),
    ("assets.deactivate", "Desativar ativos", "assets", "deactivate"),
    ("vehicles.view", "Visualizar veículos", "vehicles", "view"),
    ("vehicles.create", "Criar veículos", "vehicles", "create"),
    ("vehicles.update", "Alterar veículos", "vehicles", "update"),
    ("vehicles.deactivate", "Desativar veículos", "vehicles", "deactivate"),
    ("maintenance.view", "Visualizar manutenção", "maintenance", "view"),
    ("maintenance.create", "Criar manutenção", "maintenance", "create"),
    ("maintenance.update", "Alterar manutenção", "maintenance", "update"),
    ("maintenance.complete", "Concluir manutenção", "maintenance", "complete"),
    ("audit.view", "Visualizar auditoria", "audit", "view"),
    ("audit.export", "Exportar auditoria", "audit", "export"),
    ("settings.view", "Visualizar configurações", "settings", "view"),
    ("settings.update", "Alterar configurações", "settings", "update"),
    ("commercial_sources.view", "Visualizar origens comerciais", "commercial_sources", "view"),
    ("commercial_sources.create", "Criar origens comerciais", "commercial_sources", "create"),
    ("commercial_sources.update", "Alterar origens comerciais", "commercial_sources", "update"),
    (
        "commercial_sources.deactivate",
        "Desativar origens comerciais",
        "commercial_sources",
        "deactivate",
    ),
    ("project_types.view", "Visualizar tipos de projeto", "project_types", "view"),
    ("project_types.create", "Criar tipos de projeto", "project_types", "create"),
    ("project_types.update", "Alterar tipos de projeto", "project_types", "update"),
    ("project_types.deactivate", "Desativar tipos de projeto", "project_types", "deactivate"),
    (
        "commercial_partners.view",
        "Visualizar parceiros comerciais",
        "commercial_partners",
        "view",
    ),
    (
        "commercial_partners.create",
        "Criar parceiros comerciais",
        "commercial_partners",
        "create",
    ),
    (
        "commercial_partners.update",
        "Alterar parceiros comerciais",
        "commercial_partners",
        "update",
    ),
    (
        "commercial_partners.deactivate",
        "Desativar parceiros comerciais",
        "commercial_partners",
        "deactivate",
    ),
    ("loss_reasons.view", "Visualizar motivos de perda", "loss_reasons", "view"),
    ("loss_reasons.create", "Criar motivos de perda", "loss_reasons", "create"),
    ("loss_reasons.update", "Alterar motivos de perda", "loss_reasons", "update"),
    ("loss_reasons.deactivate", "Desativar motivos de perda", "loss_reasons", "deactivate"),
    ("service_regions.view", "Visualizar regiões de atendimento", "service_regions", "view"),
    ("service_regions.create", "Criar regiões de atendimento", "service_regions", "create"),
    ("service_regions.update", "Alterar regiões de atendimento", "service_regions", "update"),
    (
        "service_regions.deactivate",
        "Desativar regiões de atendimento",
        "service_regions",
        "deactivate",
    ),
    ("contact_channels.view", "Visualizar canais de contato", "contact_channels", "view"),
    ("contact_channels.create", "Criar canais de contato", "contact_channels", "create"),
    ("contact_channels.update", "Alterar canais de contato", "contact_channels", "update"),
    (
        "contact_channels.deactivate",
        "Desativar canais de contato",
        "contact_channels",
        "deactivate",
    ),
    ("leads.view", "Visualizar leads", "leads", "view"),
    ("leads.view_all", "Visualizar todos os leads", "leads", "view_all"),
    ("leads.view_unassigned", "Visualizar leads sem responsável", "leads", "view_unassigned"),
    ("leads.create", "Criar leads", "leads", "create"),
    ("leads.update", "Alterar leads", "leads", "update"),
    ("leads.assign", "Atribuir leads", "leads", "assign"),
    ("leads.change_status", "Alterar status de leads", "leads", "change_status"),
    ("leads.override_status", "Override de status de leads", "leads", "override_status"),
    ("leads.convert", "Converter leads em clientes", "leads", "convert"),
    ("leads.mark_won", "Marcar lead como ganho", "leads", "mark_won"),
    ("leads.mark_lost", "Marcar lead como perdido", "leads", "mark_lost"),
    ("leads.reopen", "Reabrir leads", "leads", "reopen"),
    ("lead_activities.view", "Visualizar atividades de leads", "lead_activities", "view"),
    ("lead_activities.create", "Registrar atividades de leads", "lead_activities", "create"),
    ("lead_tasks.view", "Visualizar tarefas de leads", "lead_tasks", "view"),
    ("lead_tasks.create", "Criar tarefas de leads", "lead_tasks", "create"),
    ("lead_tasks.update", "Alterar tarefas de leads", "lead_tasks", "update"),
    ("lead_tasks.complete", "Concluir tarefas de leads", "lead_tasks", "complete"),
    ("lead_tasks.cancel", "Cancelar tarefas de leads", "lead_tasks", "cancel"),
    ("lead_tasks.reopen", "Reabrir tarefas de leads", "lead_tasks", "reopen"),
    ("lead_tasks.reassign", "Reatribuir tarefas de leads", "lead_tasks", "reassign"),
    ("sales_goals.view", "Visualizar metas comerciais", "sales_goals", "view"),
    ("sales_goals.create", "Criar metas comerciais", "sales_goals", "create"),
    ("sales_goals.update", "Alterar metas comerciais", "sales_goals", "update"),
    ("sales_goals.deactivate", "Desativar metas comerciais", "sales_goals", "deactivate"),
    ("sales_score_policy.view", "Visualizar política de score", "sales_score_policy", "view"),
    ("sales_score_policy.create", "Criar política de score", "sales_score_policy", "create"),
    ("sales_score_policy.update", "Alterar política de score", "sales_score_policy", "update"),
    ("sales_score_policy.activate", "Ativar política de score", "sales_score_policy", "activate"),
    ("sales_score_events.view", "Visualizar eventos de score", "sales_score_events", "view"),
    ("sales_score_events.adjust", "Ajustar pontuação comercial", "sales_score_events", "adjust"),
    ("sales_performance.view_own", "Visualizar próprio desempenho", "sales_performance", "view_own"),
    ("sales_performance.view_all", "Visualizar desempenho da equipe", "sales_performance", "view_all"),
    ("sales_ranking.view", "Visualizar ranking comercial", "sales_ranking", "view"),
    ("sales_orders.view", "Visualizar pedidos", "sales_orders", "view"),
    ("sales_orders.create", "Criar pedidos", "sales_orders", "create"),
    ("sales_orders.update", "Alterar pedidos", "sales_orders", "update"),
    ("sales_orders.change_status", "Alterar status de pedidos", "sales_orders", "change_status"),
    ("sales_orders.cancel", "Cancelar pedidos", "sales_orders", "cancel"),
    ("production_orders.view", "Visualizar ordens de produção", "production_orders", "view"),
    ("production_orders.create", "Criar ordens de produção", "production_orders", "create"),
    ("production_orders.update", "Alterar ordens de produção", "production_orders", "update"),
    ("production_orders.change_status", "Alterar status da ordem", "production_orders", "change_status"),
    ("production_orders.start", "Iniciar ordem de produção", "production_orders", "start"),
    ("production_orders.pause", "Pausar ordem de produção", "production_orders", "pause"),
    ("production_orders.complete", "Concluir ordem de produção", "production_orders", "complete"),
    ("production_orders.cancel", "Cancelar ordem de produção", "production_orders", "cancel"),
    ("production_orders.assign", "Atribuir responsável produção", "production_orders", "assign"),
    ("production_pieces.view", "Visualizar peças", "production_pieces", "view"),
    ("production_pieces.create", "Criar peças", "production_pieces", "create"),
    ("production_pieces.update", "Alterar peças", "production_pieces", "update"),
    ("production_stages.view", "Visualizar etapas produtivas", "production_stages", "view"),
    ("production_stages.create", "Gerar etapas produtivas", "production_stages", "create"),
    ("production_stages.update", "Alterar etapas produtivas", "production_stages", "update"),
    ("production_stages.start", "Iniciar etapa produtiva", "production_stages", "start"),
    ("production_stages.complete", "Concluir etapa produtiva", "production_stages", "complete"),
    ("production_stages.skip", "Pular etapa produtiva", "production_stages", "skip"),
    ("production_logs.view", "Visualizar apontamentos", "production_logs", "view"),
    ("production_logs.create", "Registrar apontamentos", "production_logs", "create"),
    ("quality_inspections.view", "Visualizar inspeções", "quality_inspections", "view"),
    ("quality_inspections.create", "Criar inspeções", "quality_inspections", "create"),
    ("quality_inspections.inspect", "Realizar inspeções", "quality_inspections", "inspect"),
    ("quality_inspections.approve", "Aprovar inspeções", "quality_inspections", "approve"),
    ("quality_inspections.reject", "Reprovar inspeções", "quality_inspections", "reject"),
    ("deliveries.view", "Visualizar entregas", "deliveries", "view"),
    ("deliveries.schedule", "Agendar entregas", "deliveries", "schedule"),
    ("deliveries.complete", "Concluir entregas", "deliveries", "complete"),
    ("installations.view", "Visualizar instalações", "installations", "view"),
    ("installations.schedule", "Agendar instalações", "installations", "schedule"),
    ("installations.complete", "Concluir instalações", "installations", "complete"),
    ("production_dashboard.view", "Visualizar dashboard de produção", "production_dashboard", "view"),
    ("stock_dashboard.view", "Visualizar dashboard de estoque", "stock_dashboard", "view"),
    ("stock_locations.view", "Visualizar localizações", "stock_locations", "view"),
    ("stock_locations.create", "Criar localizações", "stock_locations", "create"),
    ("stock_locations.update", "Alterar localizações", "stock_locations", "update"),
    ("material_suppliers.view", "Visualizar fornecedores de material", "material_suppliers", "view"),
    ("material_suppliers.create", "Criar fornecedores de material", "material_suppliers", "create"),
    ("material_suppliers.update", "Alterar fornecedores de material", "material_suppliers", "update"),
    ("slabs.view", "Visualizar chapas", "slabs", "view"),
    ("slabs.create", "Registrar entrada de chapas", "slabs", "create"),
    ("slabs.update", "Alterar chapas", "slabs", "update"),
    ("slabs.transfer", "Transferir chapas", "slabs", "transfer"),
    ("slabs.block", "Bloquear chapas", "slabs", "block"),
    ("slabs.unblock", "Desbloquear chapas", "slabs", "unblock"),
    ("slab_reservations.view", "Visualizar reservas", "slab_reservations", "view"),
    ("slab_reservations.reserve", "Reservar chapas", "slab_reservations", "reserve"),
    ("slab_reservations.release", "Liberar reservas", "slab_reservations", "release"),
    ("slab_reservations.override_cut", "Iniciar corte sem reserva", "slab_reservations", "override_cut"),
    ("slab_consumption.consume", "Consumir chapas", "slab_consumption", "consume"),
    ("slab_losses.view", "Visualizar perdas de chapa", "slab_losses", "view"),
    ("slab_losses.create", "Registrar perdas de chapa", "slab_losses", "create"),
    ("slab_remnants.view", "Visualizar sobras", "slab_remnants", "view"),
    ("slab_remnants.create", "Registrar sobras", "slab_remnants", "create"),
    ("slab_remnants.update", "Gerenciar sobras", "slab_remnants", "update"),
    ("stock_movements.view", "Visualizar movimentações", "stock_movements", "view"),
    ("stock_inventory.view", "Visualizar inventários", "stock_inventory", "view"),
    ("stock_inventory.create", "Criar inventários", "stock_inventory", "create"),
    ("stock_inventory.inventory", "Executar inventário", "stock_inventory", "inventory"),
    ("stock_inventory.approve_inventory", "Aprovar ajustes de inventário", "stock_inventory", "approve_inventory"),
    ("stock_costs.view", "Visualizar custos de estoque", "stock_costs", "view"),
    ("stock_adjustments.execute", "Executar ajustes de estoque", "stock_adjustments", "execute"),
]
