PERMISSIONS = [
    ("dashboard.view", "Visualizar dashboard", "dashboard", "view"),
    ("users.view", "Visualizar usuários", "users", "view"),
    ("users.create", "Criar usuários", "users", "create"),
    ("users.update", "Alterar usuários", "users", "update"),
    ("users.deactivate", "Desativar usuários", "users", "deactivate"),
    ("users.manage_roles", "Gerenciar cargos de usuários", "users", "manage_roles"),
    ("roles.view", "Visualizar cargos", "roles", "view"),
    ("roles.create", "Criar cargos", "roles", "create"),
    ("roles.update", "Alterar cargos", "roles", "update"),
    ("roles.delete", "Excluir cargos", "roles", "delete"),
    (
        "roles.manage_permissions",
        "Gerenciar permissões de cargos",
        "roles",
        "manage_permissions",
    ),
    ("customers.view", "Visualizar clientes", "customers", "view"),
    ("customers.create", "Criar clientes", "customers", "create"),
    ("customers.update", "Alterar clientes", "customers", "update"),
    ("customers.deactivate", "Desativar clientes", "customers", "deactivate"),
    ("customers.export", "Exportar clientes", "customers", "export"),
    ("salespeople.view", "Visualizar vendedores", "salespeople", "view"),
    ("salespeople.create", "Criar vendedores", "salespeople", "create"),
    ("salespeople.update", "Alterar vendedores", "salespeople", "update"),
    ("salespeople.deactivate", "Desativar vendedores", "salespeople", "deactivate"),
    (
        "salespeople.view_team",
        "Visualizar equipe comercial",
        "salespeople",
        "view_team",
    ),
    ("quotes.view", "Visualizar orçamentos", "quotes", "view"),
    ("quotes.view_own", "Visualizar próprios orçamentos", "quotes", "view_own"),
    ("quotes.view_team", "Visualizar orçamentos da equipe", "quotes", "view_team"),
    ("quotes.create", "Criar orçamentos", "quotes", "create"),
    ("quotes.update", "Alterar orçamentos", "quotes", "update"),
    ("quotes.approve", "Aprovar orçamentos", "quotes", "approve"),
    ("quotes.send", "Enviar orçamentos", "quotes", "send"),
    ("quotes.cancel", "Cancelar orçamentos", "quotes", "cancel"),
    ("quotes.view_cost", "Visualizar custos de orçamentos", "quotes", "view_cost"),
    ("quotes.view_margin", "Visualizar margem de orçamentos", "quotes", "view_margin"),
    (
        "quotes.override_minimum_price",
        "Liberar preço abaixo do mínimo",
        "quotes",
        "override_minimum_price",
    ),
    (
        "quotes.manage_policy",
        "Gerenciar política comercial",
        "quotes",
        "manage_policy",
    ),
    ("materials.view", "Visualizar materiais", "materials", "view"),
    ("materials.create", "Criar materiais", "materials", "create"),
    ("materials.update", "Alterar materiais", "materials", "update"),
    ("materials.deactivate", "Desativar materiais", "materials", "deactivate"),
    (
        "materials.change_price",
        "Alterar preços de materiais",
        "materials",
        "change_price",
    ),
    ("assets.view", "Visualizar ativos", "assets", "view"),
    ("assets.create", "Criar ativos", "assets", "create"),
    ("assets.update", "Alterar ativos", "assets", "update"),
    ("assets.deactivate", "Desativar ativos", "assets", "deactivate"),
    ("vehicles.view", "Visualizar veículos", "vehicles", "view"),
    ("vehicles.create", "Criar veículos", "vehicles", "create"),
    ("vehicles.update", "Alterar veículos", "vehicles", "update"),
    ("vehicles.deactivate", "Desativar veículos", "vehicles", "deactivate"),
    ("maintenance.view", "Visualizar manutenção", "maintenance", "view"),
    ("maintenance.create", "Criar manutenção", "maintenance", "create"),
    ("maintenance.update", "Alterar manutenção", "maintenance", "update"),
    ("maintenance.complete", "Concluir manutenção", "maintenance", "complete"),
    ("audit.view", "Visualizar auditoria", "audit", "view"),
    ("audit.export", "Exportar auditoria", "audit", "export"),
    ("settings.view", "Visualizar configurações", "settings", "view"),
    ("settings.update", "Alterar configurações", "settings", "update"),
    ("commercial_sources.view", "Visualizar origens comerciais", "commercial_sources", "view"),
    ("commercial_sources.create", "Criar origens comerciais", "commercial_sources", "create"),
    ("commercial_sources.update", "Alterar origens comerciais", "commercial_sources", "update"),
    (
        "commercial_sources.deactivate",
        "Desativar origens comerciais",
        "commercial_sources",
        "deactivate",
    ),
    ("project_types.view", "Visualizar tipos de projeto", "project_types", "view"),
    ("project_types.create", "Criar tipos de projeto", "project_types", "create"),
    ("project_types.update", "Alterar tipos de projeto", "project_types", "update"),
    ("project_types.deactivate", "Desativar tipos de projeto", "project_types", "deactivate"),
    (
        "commercial_partners.view",
        "Visualizar parceiros comerciais",
        "commercial_partners",
        "view",
    ),
    (
        "commercial_partners.create",
        "Criar parceiros comerciais",
        "commercial_partners",
        "create",
    ),
    (
        "commercial_partners.update",
        "Alterar parceiros comerciais",
        "commercial_partners",
        "update",
    ),
    (
        "commercial_partners.deactivate",
        "Desativar parceiros comerciais",
        "commercial_partners",
        "deactivate",
    ),
    ("loss_reasons.view", "Visualizar motivos de perda", "loss_reasons", "view"),
    ("loss_reasons.create", "Criar motivos de perda", "loss_reasons", "create"),
    ("loss_reasons.update", "Alterar motivos de perda", "loss_reasons", "update"),
    ("loss_reasons.deactivate", "Desativar motivos de perda", "loss_reasons", "deactivate"),
    ("service_regions.view", "Visualizar regiões de atendimento", "service_regions", "view"),
    ("service_regions.create", "Criar regiões de atendimento", "service_regions", "create"),
    ("service_regions.update", "Alterar regiões de atendimento", "service_regions", "update"),
    (
        "service_regions.deactivate",
        "Desativar regiões de atendimento",
        "service_regions",
        "deactivate",
    ),
    ("contact_channels.view", "Visualizar canais de contato", "contact_channels", "view"),
    ("contact_channels.create", "Criar canais de contato", "contact_channels", "create"),
    ("contact_channels.update", "Alterar canais de contato", "contact_channels", "update"),
    (
        "contact_channels.deactivate",
        "Desativar canais de contato",
        "contact_channels",
        "deactivate",
    ),
    ("leads.view", "Visualizar leads", "leads", "view"),
    ("leads.view_all", "Visualizar todos os leads", "leads", "view_all"),
    ("leads.view_unassigned", "Visualizar leads sem responsável", "leads", "view_unassigned"),
    ("leads.create", "Criar leads", "leads", "create"),
    ("leads.update", "Alterar leads", "leads", "update"),
    ("leads.assign", "Atribuir leads", "leads", "assign"),
    ("leads.change_status", "Alterar status de leads", "leads", "change_status"),
    ("leads.override_status", "Override de status de leads", "leads", "override_status"),
    ("leads.convert", "Converter leads em clientes", "leads", "convert"),
    ("leads.mark_won", "Marcar lead como ganho", "leads", "mark_won"),
    ("leads.mark_lost", "Marcar lead como perdido", "leads", "mark_lost"),
    ("leads.reopen", "Reabrir leads", "leads", "reopen"),
    ("lead_activities.view", "Visualizar atividades de leads", "lead_activities", "view"),
    ("lead_activities.create", "Registrar atividades de leads", "lead_activities", "create"),
    ("lead_tasks.view", "Visualizar tarefas de leads", "lead_tasks", "view"),
    ("lead_tasks.create", "Criar tarefas de leads", "lead_tasks", "create"),
    ("lead_tasks.update", "Alterar tarefas de leads", "lead_tasks", "update"),
    ("lead_tasks.complete", "Concluir tarefas de leads", "lead_tasks", "complete"),
    ("lead_tasks.cancel", "Cancelar tarefas de leads", "lead_tasks", "cancel"),
    ("lead_tasks.reopen", "Reabrir tarefas de leads", "lead_tasks", "reopen"),
    ("lead_tasks.reassign", "Reatribuir tarefas de leads", "lead_tasks", "reassign"),
]
