PERMISSIONS = [
    ("dashboard.view", "Visualizar dashboard", "dashboard", "view"),
    ("users.view", "Visualizar usuários", "users", "view"),
    ("users.create", "Criar usuários", "users", "create"),
    ("users.update", "Alterar usuários", "users", "update"),
    ("users.deactivate", "Desativar usuários", "users", "deactivate"),
    ("users.manage_roles", "Gerenciar cargos de usuários", "users", "manage_roles"),
    ("roles.view", "Visualizar cargos", "roles", "view"),
    ("roles.create", "Criar cargos", "roles", "create"),
    ("roles.update", "Alterar cargos", "roles", "update"),
    ("roles.delete", "Excluir cargos", "roles", "delete"),
    (
        "roles.manage_permissions",
        "Gerenciar permissões de cargos",
        "roles",
        "manage_permissions",
    ),
    ("customers.view", "Visualizar clientes", "customers", "view"),
    ("customers.create", "Criar clientes", "customers", "create"),
    ("customers.update", "Alterar clientes", "customers", "update"),
    ("customers.deactivate", "Desativar clientes", "customers", "deactivate"),
    ("customers.export", "Exportar clientes", "customers", "export"),
    ("salespeople.view", "Visualizar vendedores", "salespeople", "view"),
    ("salespeople.create", "Criar vendedores", "salespeople", "create"),
    ("salespeople.update", "Alterar vendedores", "salespeople", "update"),
    ("salespeople.deactivate", "Desativar vendedores", "salespeople", "deactivate"),
    (
        "salespeople.view_team",
        "Visualizar equipe comercial",
        "salespeople",
        "view_team",
    ),
    ("quotes.view", "Visualizar orçamentos", "quotes", "view"),
    ("quotes.view_own", "Visualizar próprios orçamentos", "quotes", "view_own"),
    ("quotes.view_team", "Visualizar orçamentos da equipe", "quotes", "view_team"),
    ("quotes.create", "Criar orçamentos", "quotes", "create"),
    ("quotes.update", "Alterar orçamentos", "quotes", "update"),
    ("quotes.approve", "Aprovar orçamentos", "quotes", "approve"),
    ("quotes.send", "Enviar orçamentos", "quotes", "send"),
    ("quotes.cancel", "Cancelar orçamentos", "quotes", "cancel"),
    ("quotes.accept", "Aceitar orçamentos", "quotes", "accept"),
    ("quotes.refuse", "Recusar orçamentos", "quotes", "refuse"),
    ("quotes.accept_expired", "Aceitar orçamento expirado", "quotes", "accept_expired"),
    ("quotes.view_cost", "Visualizar custos de orçamentos", "quotes", "view_cost"),
    ("quotes.view_margin", "Visualizar margem de orçamentos", "quotes", "view_margin"),
    (
        "quotes.override_minimum_price",
        "Liberar preço abaixo do mínimo",
        "quotes",
        "override_minimum_price",
    ),
    (
        "quotes.manage_policy",
        "Gerenciar política comercial",
        "quotes",
        "manage_policy",
    ),
    ("materials.view", "Visualizar materiais", "materials", "view"),
    ("materials.create", "Criar materiais", "materials", "create"),
    ("materials.update", "Alterar materiais", "materials", "update"),
    ("materials.deactivate", "Desativar materiais", "materials", "deactivate"),
    (
        "materials.change_price",
        "Alterar preços de materiais",
        "materials",
        "change_price",
    ),
    ("assets.view", "Visualizar ativos", "assets", "view"),
    ("assets.create", "Criar ativos", "assets", "create"),
    ("assets.update", "Alterar ativos", "assets", "update"),
    ("assets.deactivate", "Desativar ativos", "assets", "deactivate"),
    ("vehicles.view", "Visualizar veículos", "vehicles", "view"),
    ("vehicles.create", "Criar veículos", "vehicles", "create"),
    ("vehicles.update", "Alterar veículos", "vehicles", "update"),
    ("vehicles.deactivate", "Desativar veículos", "vehicles", "deactivate"),
    ("maintenance.view", "Visualizar manutenção", "maintenance", "view"),
    ("maintenance.create", "Criar manutenção", "maintenance", "create"),
    ("maintenance.update", "Alterar manutenção", "maintenance", "update"),
    ("maintenance.complete", "Concluir manutenção", "maintenance", "complete"),
    ("audit.view", "Visualizar auditoria", "audit", "view"),
    ("audit.export", "Exportar auditoria", "audit", "export"),
    ("settings.view", "Visualizar configurações", "settings", "view"),
    ("settings.update", "Alterar configurações", "settings", "update"),
    ("commercial_sources.view", "Visualizar origens comerciais", "commercial_sources", "view"),
    ("commercial_sources.create", "Criar origens comerciais", "commercial_sources", "create"),
    ("commercial_sources.update", "Alterar origens comerciais", "commercial_sources", "update"),
    (
        "commercial_sources.deactivate",
        "Desativar origens comerciais",
        "commercial_sources",
        "deactivate",
    ),
    ("project_types.view", "Visualizar tipos de projeto", "project_types", "view"),
    ("project_types.create", "Criar tipos de projeto", "project_types", "create"),
    ("project_types.update", "Alterar tipos de projeto", "project_types", "update"),
    ("project_types.deactivate", "Desativar tipos de projeto", "project_types", "deactivate"),
    (
        "commercial_partners.view",
        "Visualizar parceiros comerciais",
        "commercial_partners",
        "view",
    ),
    (
        "commercial_partners.create",
        "Criar parceiros comerciais",
        "commercial_partners",
        "create",
    ),
    (
        "commercial_partners.update",
        "Alterar parceiros comerciais",
        "commercial_partners",
        "update",
    ),
    (
        "commercial_partners.deactivate",
        "Desativar parceiros comerciais",
        "commercial_partners",
        "deactivate",
    ),
    ("loss_reasons.view", "Visualizar motivos de perda", "loss_reasons", "view"),
    ("loss_reasons.create", "Criar motivos de perda", "loss_reasons", "create"),
    ("loss_reasons.update", "Alterar motivos de perda", "loss_reasons", "update"),
    ("loss_reasons.deactivate", "Desativar motivos de perda", "loss_reasons", "deactivate"),
    ("service_regions.view", "Visualizar regiões de atendimento", "service_regions", "view"),
    ("service_regions.create", "Criar regiões de atendimento", "service_regions", "create"),
    ("service_regions.update", "Alterar regiões de atendimento", "service_regions", "update"),
    (
        "service_regions.deactivate",
        "Desativar regiões de atendimento",
        "service_regions",
        "deactivate",
    ),
    ("contact_channels.view", "Visualizar canais de contato", "contact_channels", "view"),
    ("contact_channels.create", "Criar canais de contato", "contact_channels", "create"),
    ("contact_channels.update", "Alterar canais de contato", "contact_channels", "update"),
    (
        "contact_channels.deactivate",
        "Desativar canais de contato",
        "contact_channels",
        "deactivate",
    ),
    ("leads.view", "Visualizar leads", "leads", "view"),
    ("leads.view_all", "Visualizar todos os leads", "leads", "view_all"),
    ("leads.view_unassigned", "Visualizar leads sem responsável", "leads", "view_unassigned"),
    ("leads.create", "Criar leads", "leads", "create"),
    ("leads.update", "Alterar leads", "leads", "update"),
    ("leads.assign", "Atribuir leads", "leads", "assign"),
    ("leads.change_status", "Alterar status de leads", "leads", "change_status"),
    ("leads.override_status", "Override de status de leads", "leads", "override_status"),
    ("leads.convert", "Converter leads em clientes", "leads", "convert"),
    ("leads.mark_won", "Marcar lead como ganho", "leads", "mark_won"),
    ("leads.mark_lost", "Marcar lead como perdido", "leads", "mark_lost"),
    ("leads.reopen", "Reabrir leads", "leads", "reopen"),
    ("lead_activities.view", "Visualizar atividades de leads", "lead_activities", "view"),
    ("lead_activities.create", "Registrar atividades de leads", "lead_activities", "create"),
    ("lead_tasks.view", "Visualizar tarefas de leads", "lead_tasks", "view"),
    ("lead_tasks.create", "Criar tarefas de leads", "lead_tasks", "create"),
    ("lead_tasks.update", "Alterar tarefas de leads", "lead_tasks", "update"),
    ("lead_tasks.complete", "Concluir tarefas de leads", "lead_tasks", "complete"),
    ("lead_tasks.cancel", "Cancelar tarefas de leads", "lead_tasks", "cancel"),
    ("lead_tasks.reopen", "Reabrir tarefas de leads", "lead_tasks", "reopen"),
    ("lead_tasks.reassign", "Reatribuir tarefas de leads", "lead_tasks", "reassign"),
    ("sales_goals.view", "Visualizar metas comerciais", "sales_goals", "view"),
    ("sales_goals.create", "Criar metas comerciais", "sales_goals", "create"),
    ("sales_goals.update", "Alterar metas comerciais", "sales_goals", "update"),
    ("sales_goals.deactivate", "Desativar metas comerciais", "sales_goals", "deactivate"),
    ("sales_score_policy.view", "Visualizar política de score", "sales_score_policy", "view"),
    ("sales_score_policy.create", "Criar política de score", "sales_score_policy", "create"),
    ("sales_score_policy.update", "Alterar política de score", "sales_score_policy", "update"),
    ("sales_score_policy.activate", "Ativar política de score", "sales_score_policy", "activate"),
    ("sales_score_events.view", "Visualizar eventos de score", "sales_score_events", "view"),
    ("sales_score_events.adjust", "Ajustar pontuação comercial", "sales_score_events", "adjust"),
    ("sales_performance.view_own", "Visualizar próprio desempenho", "sales_performance", "view_own"),
    ("sales_performance.view_all", "Visualizar desempenho da equipe", "sales_performance", "view_all"),
    ("sales_ranking.view", "Visualizar ranking comercial", "sales_ranking", "view"),
    ("sales_orders.view", "Visualizar pedidos", "sales_orders", "view"),
    ("sales_orders.create", "Criar pedidos", "sales_orders", "create"),
    ("sales_orders.update", "Alterar pedidos", "sales_orders", "update"),
    ("sales_orders.change_status", "Alterar status de pedidos", "sales_orders", "change_status"),
    ("sales_orders.cancel", "Cancelar pedidos", "sales_orders", "cancel"),
    ("production_orders.view", "Visualizar ordens de produção", "production_orders", "view"),
    ("production_orders.create", "Criar ordens de produção", "production_orders", "create"),
    ("production_orders.update", "Alterar ordens de produção", "production_orders", "update"),
    ("production_orders.change_status", "Alterar status da ordem", "production_orders", "change_status"),
    ("production_orders.start", "Iniciar ordem de produção", "production_orders", "start"),
    ("production_orders.pause", "Pausar ordem de produção", "production_orders", "pause"),
    ("production_orders.complete", "Concluir ordem de produção", "production_orders", "complete"),
    ("production_orders.cancel", "Cancelar ordem de produção", "production_orders", "cancel"),
    ("production_orders.assign", "Atribuir responsável produção", "production_orders", "assign"),
    ("production_pieces.view", "Visualizar peças", "production_pieces", "view"),
    ("production_pieces.create", "Criar peças", "production_pieces", "create"),
    ("production_pieces.update", "Alterar peças", "production_pieces", "update"),
    ("production_stages.view", "Visualizar etapas produtivas", "production_stages", "view"),
    ("production_stages.create", "Gerar etapas produtivas", "production_stages", "create"),
    ("production_stages.update", "Alterar etapas produtivas", "production_stages", "update"),
    ("production_stages.start", "Iniciar etapa produtiva", "production_stages", "start"),
    ("production_stages.complete", "Concluir etapa produtiva", "production_stages", "complete"),
    ("production_stages.skip", "Pular etapa produtiva", "production_stages", "skip"),
    ("production_logs.view", "Visualizar apontamentos", "production_logs", "view"),
    ("production_logs.create", "Registrar apontamentos", "production_logs", "create"),
    ("quality_inspections.view", "Visualizar inspeções", "quality_inspections", "view"),
    ("quality_inspections.create", "Criar inspeções", "quality_inspections", "create"),
    ("quality_inspections.inspect", "Realizar inspeções", "quality_inspections", "inspect"),
    ("quality_inspections.approve", "Aprovar inspeções", "quality_inspections", "approve"),
    ("quality_inspections.reject", "Reprovar inspeções", "quality_inspections", "reject"),
    ("deliveries.view", "Visualizar entregas", "deliveries", "view"),
    ("deliveries.schedule", "Agendar entregas", "deliveries", "schedule"),
    ("deliveries.complete", "Concluir entregas", "deliveries", "complete"),
    ("installations.view", "Visualizar instalações", "installations", "view"),
    ("installations.schedule", "Agendar instalações", "installations", "schedule"),
    ("installations.complete", "Concluir instalações", "installations", "complete"),
    ("production_dashboard.view", "Visualizar dashboard de produção", "production_dashboard", "view"),
    ("stock_dashboard.view", "Visualizar dashboard de estoque", "stock_dashboard", "view"),
    ("stock_locations.view", "Visualizar localizações", "stock_locations", "view"),
    ("stock_locations.create", "Criar localizações", "stock_locations", "create"),
    ("stock_locations.update", "Alterar localizações", "stock_locations", "update"),
    ("material_suppliers.view", "Visualizar fornecedores de material", "material_suppliers", "view"),
    ("material_suppliers.create", "Criar fornecedores de material", "material_suppliers", "create"),
    ("material_suppliers.update", "Alterar fornecedores de material", "material_suppliers", "update"),
    ("slabs.view", "Visualizar chapas", "slabs", "view"),
    ("slabs.create", "Registrar entrada de chapas", "slabs", "create"),
    ("slabs.update", "Alterar chapas", "slabs", "update"),
    ("slabs.transfer", "Transferir chapas", "slabs", "transfer"),
    ("slabs.block", "Bloquear chapas", "slabs", "block"),
    ("slabs.unblock", "Desbloquear chapas", "slabs", "unblock"),
    ("slab_reservations.view", "Visualizar reservas", "slab_reservations", "view"),
    ("slab_reservations.reserve", "Reservar chapas", "slab_reservations", "reserve"),
    ("slab_reservations.release", "Liberar reservas", "slab_reservations", "release"),
    ("slab_reservations.override_cut", "Iniciar corte sem reserva", "slab_reservations", "override_cut"),
    ("slab_consumption.consume", "Consumir chapas", "slab_consumption", "consume"),
    ("slab_losses.view", "Visualizar perdas de chapa", "slab_losses", "view"),
    ("slab_losses.create", "Registrar perdas de chapa", "slab_losses", "create"),
    ("slab_remnants.view", "Visualizar sobras", "slab_remnants", "view"),
    ("slab_remnants.create", "Registrar sobras", "slab_remnants", "create"),
    ("slab_remnants.update", "Gerenciar sobras", "slab_remnants", "update"),
    ("stock_movements.view", "Visualizar movimentações", "stock_movements", "view"),
    ("stock_inventory.view", "Visualizar inventários", "stock_inventory", "view"),
    ("stock_inventory.create", "Criar inventários", "stock_inventory", "create"),
    ("stock_inventory.inventory", "Executar inventário", "stock_inventory", "inventory"),
    ("stock_inventory.approve_inventory", "Aprovar ajustes de inventário", "stock_inventory", "approve_inventory"),
    ("stock_costs.view", "Visualizar custos de estoque", "stock_costs", "view"),
    ("stock_adjustments.execute", "Executar ajustes de estoque", "stock_adjustments", "execute"),
    ("operational_events.view", "Visualizar eventos da agenda", "operational_events", "view"),
    ("operational_events.view_all", "Visualizar toda a agenda", "operational_events", "view_all"),
    ("operational_events.create", "Criar eventos da agenda", "operational_events", "create"),
    ("operational_events.update", "Alterar eventos da agenda", "operational_events", "update"),
    ("operational_events.assign", "Atribuir eventos da agenda", "operational_events", "assign"),
    ("operational_events.confirm", "Confirmar eventos da agenda", "operational_events", "confirm"),
    ("operational_events.start", "Iniciar eventos da agenda", "operational_events", "start"),
    ("operational_events.complete", "Concluir eventos da agenda", "operational_events", "complete"),
    ("operational_events.reschedule", "Reagendar eventos", "operational_events", "reschedule"),
    ("operational_events.cancel", "Cancelar eventos da agenda", "operational_events", "cancel"),
    (
        "operational_events.override_conflict",
        "Sobrescrever conflito de agenda",
        "operational_events",
        "override_conflict",
    ),
    ("schedule_dashboard.view", "Visualizar dashboard da agenda", "schedule_dashboard", "view"),
    ("schedule_calendar.view", "Visualizar calendário operacional", "schedule_calendar", "view"),
    ("schedule_measurements.view", "Visualizar medições", "schedule_measurements", "view"),
    ("schedule_measurements.create", "Criar medições", "schedule_measurements", "create"),
    ("schedule_measurements.update", "Alterar medições", "schedule_measurements", "update"),
    ("after_sales_cases.view", "Visualizar casos de pós-venda", "after_sales_cases", "view"),
    ("after_sales_cases.view_all", "Visualizar todos os casos de pós-venda", "after_sales_cases", "view_all"),
    ("after_sales_cases.create", "Criar casos de pós-venda", "after_sales_cases", "create"),
    ("after_sales_cases.update", "Alterar casos de pós-venda", "after_sales_cases", "update"),
    ("after_sales_cases.assign", "Atribuir casos de pós-venda", "after_sales_cases", "assign"),
    ("after_sales_cases.change_status", "Alterar status de casos", "after_sales_cases", "change_status"),
    ("after_sales_cases.diagnose", "Diagnosticar casos", "after_sales_cases", "diagnose"),
    ("after_sales_cases.resolve", "Resolver casos", "after_sales_cases", "resolve"),
    ("after_sales_cases.close", "Fechar casos", "after_sales_cases", "close"),
    ("after_sales_cases.reopen", "Reabrir casos", "after_sales_cases", "reopen"),
    ("after_sales_cases.reject", "Rejeitar casos", "after_sales_cases", "reject"),
    ("after_sales_cases.cancel", "Cancelar casos", "after_sales_cases", "cancel"),
    ("warranties.view", "Visualizar garantias", "warranties", "view"),
    ("warranties.create", "Criar garantias", "warranties", "create"),
    ("warranties.update", "Alterar garantias", "warranties", "update"),
    ("warranties.decide", "Decidir elegibilidade de garantia", "warranties", "decide"),
    ("installation_pending_items.view", "Visualizar pendências de instalação", "installation_pending_items", "view"),
    ("installation_pending_items.create", "Criar pendências de instalação", "installation_pending_items", "create"),
    ("installation_pending_items.update", "Alterar pendências de instalação", "installation_pending_items", "update"),
    ("customer_satisfaction.view", "Visualizar pesquisas de satisfação", "customer_satisfaction", "view"),
    ("customer_satisfaction.create", "Criar pesquisas de satisfação", "customer_satisfaction", "create"),
    ("customer_satisfaction.update", "Registrar respostas de satisfação", "customer_satisfaction", "update"),
    ("review_requests.view", "Visualizar solicitações de avaliação", "review_requests", "view"),
    ("review_requests.create", "Criar solicitações de avaliação", "review_requests", "create"),
    ("review_requests.update", "Atualizar solicitações de avaliação", "review_requests", "update"),
    ("media_usage_consents.view", "Visualizar autorizações de imagem", "media_usage_consents", "view"),
    ("media_usage_consents.create", "Registrar autorizações de imagem", "media_usage_consents", "create"),
    ("media_usage_consents.update", "Atualizar autorizações de imagem", "media_usage_consents", "update"),
    ("customer_referrals.view", "Visualizar indicações", "customer_referrals", "view"),
    ("customer_referrals.create", "Registrar indicações", "customer_referrals", "create"),
    ("customer_referrals.update", "Atualizar indicações", "customer_referrals", "update"),
    ("customer_referrals.convert", "Converter indicação em lead", "customer_referrals", "convert"),
    ("after_sales_dashboard.view", "Visualizar dashboard de pós-venda", "after_sales_dashboard", "view"),
    ("media_assets.view", "Visualizar mídias", "media_assets", "view"),
    ("media_assets.view_all", "Visualizar todas as mídias", "media_assets", "view_all"),
    ("media_assets.upload", "Enviar mídias", "media_assets", "upload"),
    ("media_assets.update", "Alterar mídias", "media_assets", "update"),
    ("media_assets.classify", "Classificar mídias", "media_assets", "classify"),
    ("media_assets.review", "Revisar mídias", "media_assets", "review"),
    ("media_assets.approve", "Aprovar mídias", "media_assets", "approve"),
    ("media_assets.reject", "Rejeitar mídias", "media_assets", "reject"),
    ("media_assets.archive", "Arquivar mídias", "media_assets", "archive"),
    ("media_assets.request_delete", "Solicitar exclusão de mídias", "media_assets", "request_delete"),
    ("media_collections.view", "Visualizar coleções de mídia", "media_collections", "view"),
    ("media_collections.create", "Criar coleções de mídia", "media_collections", "create"),
    ("media_collections.update", "Alterar coleções de mídia", "media_collections", "update"),
    ("media_portfolio.view", "Visualizar portfólio interno", "media_portfolio", "view"),
    ("media_portfolio.approve", "Aprovar mídia para portfólio", "media_portfolio", "approve"),
    ("media_publication_candidates.view", "Visualizar candidatos de publicação", "media_publication_candidates", "view"),
    ("media_publication_candidates.create", "Criar candidatos de publicação", "media_publication_candidates", "create"),
    ("media_publication_candidates.update", "Alterar candidatos de publicação", "media_publication_candidates", "update"),
    ("media_private_files.view", "Acessar arquivos privados de mídia", "media_private_files", "view"),
    ("media_dashboard.view", "Visualizar dashboard de mídia", "media_dashboard", "view"),
]
