# Generated by Django 6.0.7 on 2026-08-02 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_leadsequence_lead_leadactivity_leadtask_and_more'),
        ('quotes', '0002_quote_commercial_source_quote_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='commercial.lead'),
        ),
    ]
