# Generated by Django 6.0.7 on 2026-08-02 10:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0003_salesscorepolicy_salesscoreevent_salesgoal_and_more'),
        ('finance', '0001_initial'),
        ('production', '0001_initial'),
        ('quotes', '0004_quoteacceptance'),
        ('salespeople', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('commission_target', models.CharField(choices=[('salesperson', 'Vendedor'), ('commercial_partner', 'Parceiro'), ('both', 'Ambos')], default='salesperson', max_length=30)),
                ('calculation_basis', models.CharField(choices=[('gross_order_value', 'Valor bruto do pedido'), ('net_order_value', 'Valor líquido do pedido'), ('received_value', 'Valor recebido'), ('item_value', 'Valor de itens'), ('service_value', 'Valor de serviços'), ('margin_value', 'Valor da margem'), ('custom', 'Personalizado')], default='net_order_value', max_length=30)),
                ('trigger_type', models.CharField(choices=[('quote_accepted', 'Orçamento aceito'), ('order_confirmed', 'Pedido confirmado'), ('receivable_generated', 'Conta a receber gerada'), ('payment_received', 'Recebimento'), ('order_completed', 'Pedido concluído'), ('manual', 'Manual')], default='quote_accepted', max_length=30)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('requires_approval', models.BooleanField(default=False)),
                ('release_only_after_payment', models.BooleanField(default=True)),
                ('minimum_margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('maximum_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', '-valid_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('minimum_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('minimum_margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('override_commission_type', models.CharField(blank=True, choices=[('percentage', 'Percentual'), ('fixed_amount', 'Valor fixo'), ('percentage_over_margin', 'Percentual sobre margem')], max_length=30)),
                ('override_commission_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('commercial_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='commercial.commercialpartner')),
                ('commercial_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_rules', to='commercial.commercialsource')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='commissions.commissionpolicy')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_rules', to='commercial.projecttype')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='salespeople.salesperson')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommissionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('year', models.PositiveIntegerField()),
                ('current', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'year'), name='unique_commission_seq_kind_year')],
            },
        ),
        migrations.CreateModel(
            name='CommissionSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('beneficiary_type', models.CharField(choices=[('salesperson', 'Vendedor'), ('commercial_partner', 'Parceiro')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('under_review', 'Em análise'), ('approved', 'Aprovado'), ('partially_paid', 'Parcialmente pago'), ('paid', 'Pago'), ('closed', 'Encerrado'), ('cancelled', 'Cancelado')], default='draft', max_length=30)),
                ('provisioned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('available_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reversed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_settlements_approved', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_settlements_closed', to=settings.AUTH_USER_MODEL)),
                ('commercial_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_settlements', to='commercial.commercialpartner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_settlements', to='finance.accountspayable')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_settlements', to='salespeople.salesperson')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('reversed', 'Estornado'), ('cancelled', 'Cancelado')], default='confirmed', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payments_created', to=settings.AUTH_USER_MODEL)),
                ('financial_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payments', to='finance.financialaccount')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payments', to='finance.paymentmethod')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commissions.commissionsettlement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('beneficiary_type', models.CharField(choices=[('salesperson', 'Vendedor'), ('commercial_partner', 'Parceiro')], max_length=30)),
                ('beneficiary_name_snapshot', models.CharField(blank=True, max_length=180)),
                ('beneficiary_document_snapshot', models.CharField(blank=True, max_length=40)),
                ('event_type', models.CharField(choices=[('provision', 'Provisionamento'), ('release', 'Liberação'), ('payment', 'Pagamento'), ('reversal', 'Estorno'), ('adjustment_positive', 'Ajuste positivo'), ('adjustment_negative', 'Ajuste negativo'), ('cancellation', 'Cancelamento'), ('chargeback', 'Chargeback')], max_length=30)),
                ('status', models.CharField(choices=[('provisioned', 'Provisionada'), ('pending_approval', 'Aguardando aprovação'), ('approved', 'Aprovada'), ('available', 'Disponível'), ('partially_paid', 'Parcialmente paga'), ('paid', 'Paga'), ('reversed', 'Estornada'), ('cancelled', 'Cancelada'), ('blocked', 'Bloqueada')], default='provisioned', max_length=30)),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.PositiveIntegerField()),
                ('calculation_basis_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('eligible_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('event_date', models.DateField()),
                ('competence_date', models.DateField()),
                ('available_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('commercial_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_events', to='commercial.commercialpartner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_events_created', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_events', to='quotes.quote')),
                ('receivable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_events', to='finance.accountsreceivable')),
                ('receivable_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_events', to='finance.receivablepayment')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='commissions.commissionevent')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_events', to='production.salesorder')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_events', to='salespeople.salesperson')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='commissions.commissionpolicy')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='commissions.commissionrule')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='commissions.commissionsettlement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionSettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('included_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='included', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('commission_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_items', to='commissions.commissionevent')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commissions.commissionsettlement')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionPolicyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('minimum_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('maximum_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentual'), ('fixed_amount', 'Valor fixo'), ('percentage_over_margin', 'Percentual sobre margem')], default='percentage', max_length=30)),
                ('commission_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('applies_to_excess', models.BooleanField(default=False)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='commissions.commissionpolicy')),
            ],
            options={
                'ordering': ['sequence', 'minimum_value'],
                'unique_together': {('policy', 'sequence')},
            },
        ),
        migrations.AddIndex(
            model_name='commissionevent',
            index=models.Index(fields=['event_type', 'status'], name='commissions_event_t_a69409_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionevent',
            index=models.Index(fields=['salesperson', 'status'], name='commissions_salespe_9f97f9_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionevent',
            index=models.Index(fields=['commercial_partner', 'status'], name='commissions_commerc_3be703_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionevent',
            index=models.Index(fields=['source_type', 'source_id'], name='commissions_source__b16b2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionevent',
            constraint=models.UniqueConstraint(condition=models.Q(('salesperson__isnull', False), models.Q(('status__in', ['reversed', 'cancelled']), _negated=True), models.Q(('event_type__in', ['reversal', 'adjustment_positive', 'adjustment_negative']), _negated=True)), fields=('event_type', 'source_type', 'source_id', 'beneficiary_type', 'salesperson'), name='unique_active_commission_event_salesperson'),
        ),
        migrations.AddConstraint(
            model_name='commissionevent',
            constraint=models.UniqueConstraint(condition=models.Q(('commercial_partner__isnull', False), models.Q(('status__in', ['reversed', 'cancelled']), _negated=True), models.Q(('event_type__in', ['reversal', 'adjustment_positive', 'adjustment_negative']), _negated=True)), fields=('event_type', 'source_type', 'source_id', 'beneficiary_type', 'commercial_partner'), name='unique_active_commission_event_partner'),
        ),
        migrations.AlterUniqueTogether(
            name='commissionsettlementitem',
            unique_together={('settlement', 'commission_event')},
        ),
    ]
