# Generated by Django 5.0.11 on 2026-07-25 03:16

import django.db.models.deletion
import django.utils.timezone
import materials.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('linear_meter', 'Metro linear'), ('unit', 'Unidade'), ('m2', 'm²'), ('service', 'Serviço')], default='service', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[materials.models.validate_non_negative])),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[materials.models.validate_non_negative])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('linear_meter', 'Metro linear'), ('unit', 'Unidade'), ('m2', 'm²'), ('service', 'Serviço')], default='linear_meter', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[materials.models.validate_non_negative])),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[materials.models.validate_non_negative])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'categoria de material',
                'verbose_name_plural': 'categorias de materiais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('origin', models.CharField(blank=True, max_length=120)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('finish', models.CharField(blank=True, max_length=80)),
                ('thickness_mm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[materials.models.validate_non_negative])),
                ('unit', models.CharField(choices=[('m2', 'm²'), ('linear_meter', 'Metro linear'), ('unit', 'Unidade'), ('kg', 'Kg'), ('sheet', 'Chapa'), ('service', 'Serviço')], default='m2', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[materials.models.validate_non_negative])),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[materials.models.validate_non_negative])),
                ('minimum_sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[materials.models.validate_non_negative])),
                ('loss_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[materials.models.validate_percentage])),
                ('default_margin_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[materials.models.validate_percentage])),
                ('is_stock_controlled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.materialcategory')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('cost', 'Custo'), ('sale', 'Venda'), ('minimum_sale', 'Venda mínima')], max_length=20)),
                ('old_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='materials.material')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('slab_code', models.CharField(max_length=60, unique=True)),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('supplier', models.CharField(blank=True, max_length=160)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=10, validators=[materials.models.validate_non_negative])),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=10, validators=[materials.models.validate_non_negative])),
                ('thickness_mm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[materials.models.validate_non_negative])),
                ('area_m2', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('cost_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[materials.models.validate_non_negative])),
                ('location', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('reserved', 'Reservada'), ('used', 'Utilizada'), ('damaged', 'Danificada'), ('discarded', 'Descartada')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slabs', to='materials.material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slab_code'],
            },
        ),
    ]
