# Generated by Django 6.0.7 on 2026-08-02 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_stock_phase05'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='materials_s_referen_a766f2_idx',
            old_name='materials_s_referen_6a0fbd_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='materials_s_slab_id_48ee81_idx',
            old_name='materials_s_slab_id_8ea0d1_idx',
        ),
    ]
